[tests] Drop test for removed deprecated methods
Commit d203902 removed our deprecated new_ns() and new_title() methods but
not the corresponding test, causing our unit tests to fail...

  % python -m tests.logentries_tests TestDeprecatedMethods

  ======================================================================
  ERROR: test_move_entry_dewp (__main__.TestDeprecatedMethods)
  Test deprecated MoveEntry methods on wikipedia:de
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/home/atagar/pywikibot/core/tests/aspects.py", line 626, in wrapped_method
      func(self, key)
    File "/home/atagar/pywikibot/core/tests/logentries_tests.py", line 298, in test_move_entry
      self.assertIsInstance(logentry.new_ns(), int)
    File "/home/atagar/pywikibot/core/pywikibot/logentries.py", line 92, in __getattr__
      return super().__getattribute__(item)
  AttributeError: 'MoveEntry' object has no attribute 'new_ns'

Change-Id: I0e4bd3251d26626895f4b517f1652b2cc8f3177e