PageLoadInconsistentTitle exception for inconsistent page-loading results
Errors for inconsistent page-loading results have been standardized.

Previously the same situation may have caused
"AttributeError: 'Page' object has no attribute '_pageid'"
which was harder to decipher. See T94826.

The new message does not include the method name itself; see
the stack trace instead.

Change-Id: I554417d81718158effe9bd3b1d233aa91a3464ef