Revert "[IMPR] Always close files finally in throttle.py"
Fails if file cannot be opened:
    f.close()

UnboundLocalError: local variable 'f' referenced before assignment

This reverts commit 98fd8fb74998c08a9f1fac4031297bb007848b57.

Change-Id: I044dcf3ff44153d2e754f8b85f03aa16f33fbaf3