Use 'summary' instead of 'comment' in page.save()
This change is necessary because firstly 'summary' is being used
in mediawiki's API and so people tend to use summary more than comment.
Secondly since currently summary is automatically being passed to API,
using summary instead of comment currently can cause odd behavior. [1]
Thirdly comment is not a correct word (or the best word) to describe
an edit summary.

All usages of Page.save(), Page.put(), Bot.userPut(), Bot.put_current()
Page.put_async() should change this argument.

[1]:
>>> page.save(summary='ok')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pywikibot/tools/__init__.py", line 949, in wrapper
    return obj(*__args, **__kw)
  File "pywikibot/page.py", line 1042, in save
    **kwargs)
  File "pywikibot/page.py", line 1048, in _save
    err = None
TypeError: editpage() got multiple values for keyword argument 'summary'

Change-Id: Ib5fde07a587f82a11dd1fd1e8c326883cd6616ea