[bugfix] assign total variable to None in first step
Initialize total variable to None. Otherwise an error may occur
e.g. if all named parameters are None:
UnboundLocalError: local variable 'total' referenced before assignment

Change-Id: I2b4f6a4be834a1098957ec4d73b91a73bdb45421