[IMPR] Add WikibaseFamily and DefaultWikibaseFamily class to family.py
- Add WikibaseFamily which holds default settings for a Wikibase like
  interface and entity_sources.
- Add DefaultWikibaseFamily which holds default settings for
  calendarmodel, default_globe and globes
- derive commons_family.Family and wikidata_family.Family from
  DefaultWikibaseFamily to prevent code duplication
- derive lingualibre_family.Family from WikibaseFamily to add the
  missing entity_sources. Otherwise an
  AttributeError: DataSite instance has no attribute 'entity_sources
  will arrise.

See also: https://www.mediawiki.org/wiki/Topic:Xl9dhs135tuqj6w6

Change-Id: Ic7423c82f9635ef8e5e7b86fc73d49c2eae17116