[bugfix] Tests fail if family is named 'test'
This file had a vestigial conditional for the 'test' family that was removed in
commit 66d88aa. This causes a test failure for me because I coincidently chose
the same name.

  ======================================================================
  FAIL: test_each_family (tests.family_tests.TestFamilyUrlRegex) (family='test')
  Test each family builds a working regex.
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "pywikibot/tests/family_tests.py", line 235, in test_each_family
      self.assertEqual(family.from_url(url), code)
    File "pywikibot/pywikibot/family.py", line 864, in from_url
      site = pywikibot.Site(code, self.name)
    File "pywikibot/tests/family_tests.py", line 161, in Site
      self.assertEqual(fam, 'wikipedia')
  AssertionError: 'test' != 'wikipedia'
  - test
  + wikipedia

Bug: T287332
Change-Id: I4cdba4acfda166375a8edcabe74d735f86fec235