movepages.py: prevent error message with from/to
Prevent to display error message:

    ERROR: Unable to execute script because no generator was defined.

when -from -to are used to specify input.

Change-Id: I96a3cea2f0fd959379a0fc67d8ed5c978217eda1