Bugfix for older mediawiki short monthsnames
- older short months names sometimes didn't ends with a
  abbreviating dot. This causes the TimeStripper to fail with with
  "incorrect month name in page",
  TypeError: an integer is required
  This path also registers undotted short months names to be
  compared.
- start enumerate() with start=1

Change-Id: I25f467620b79fd39fba20e45aaeb0386b50101e4