Revert "convert html text to unicode, read charset, use utf-8 by default"
New bug:
Retrieving 50 pages from wikipedia:en.
ERROR: Traceback (most recent call last):
  File "C:\pwb\core\pywikibot\data\api.py", line 291, in submit
    body=paramstring)
  File "C:\pwb\core\pywikibot\comms\http.py", line 156, in request
    text = unicode(text, charset, errors='strict')
LookupError: unknown encoding: \

WARNING: Waiting 5 seconds before retrying.
ERROR: Traceback (most recent call last):
  File "C:\pwb\core\pywikibot\data\api.py", line 291, in submit
    body=paramstring)
  File "C:\pwb\core\pywikibot\comms\http.py", line 156, in request
    text = unicode(text, charset, errors='strict')
LookupError: unknown encoding: \

WARNING: Waiting 10 seconds before retrying.

This reverts commit 3a258d28d608c55e9113c4aa36061927d0b054fa.

Change-Id: Ife8f24b20eeb22302c915b32d0cd106d83903e1d