[BUGFIX] Allow Exception as parameter of pywikibot.exceptions.Error
Exceptions may be parameters of Exceptions calls. You can do this

 def f():
     try:
         1/0
     except ZeroDivisionError as e:
         raise RuntimeError(e)

 try:
     f()
 except Exception as e:
     print('### {} ###'.format(e))

Trying this with pywikibot.Error lead to a
TypeError: __str__ returned non-string

Therefore enable Exception as parameter of pywikibot.Error

Change-Id: Ib53dc2d53fa27d2a7d15e3e959837e00f6499e72