[tests] Do not use pytest 4.1.0 with pytest-cov < 2.6.1
pytest 4.1.0 causes a lot of failures
AttributeError: 'TestCaseFunction' object has no attribute 'get_marker'
see https://api.travis-ci.org/v3/job/476035849/log.txt

Change-Id: Ia292cbaed69e923e19ce466ed638b9126ff9e60d