test_bot_may_edit_general: Make sure `ignore_bot_templates` is False
Previously, if ignore_bot_templates was set to True in user-config.py, the test
would have failed with the following error:

Failure
Traceback (most recent call last):
  File "...\pywikibot-core\tests\page_tests.py", line 709, in test_bot_may_edit_general
    self.assertFalse(page.botMayEdit())
AssertionError: True is not false

Change-Id: I4118b2cb42950e030fa81f70ff8b06e54233758e