[bugfix] Fix nowcommons test failure
By moving the nowcommons script in commit fd16ca1ff it got unit test coverage.
Fixing its test failure...

  % python -m tests.script_tests TestScriptSimulate
  ...
  ======================================================================
  FAIL: test_nowcommons (tests.script_tests.TestScriptSimulate)
  Test running nowcommons -simulate.
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "pywikibot/tests/script_tests.py", line 243, in testScript
      self.assertIn('Use -help for further information.',
  AssertionError: 'Use -help for further information.' not found in ['No
  transcluded files found for NowCommons.', '', '0 pages read', '0 pages
  written', '0 pages skipped', 'Script terminated successfully.']

  ----------------------------------------------------------------------

Change-Id: If504d72e3e67a31b3fb3d32fcb36a17deb40752d