version.py: Remove line endings in getversion_nightly
The version strings are eventually passed into the user agent, and
having a linebreak results in a user agent such as:

  script (wikipedia:test; User:Bot) Pywikibot/9.2.0.dev1 (1\n)
    requests/2.28.2 Python/3.9.2.final.0

This \n causes the result to fail with error:

  pywikibot.exceptions.FatalServerError: Invalid leading whitespace,
    reserved character(s), or returncharacter(s) in header value.

Fix this by, instead of using readlines, which preserves the line
endings, read the entire file and split by linebreak, which implicitly
removes all the line endings.

Bug: T363943
Change-Id: I38f9b27d3339916dc6b784ecda602055924aa6bc