distutils build_modules requires str on Python 2
When setup parameter packages contains unicode, distutils fails with:

    TypeError: 'package' must be a string (dot-separated), list, or tuple

Bug: T114487
Change-Id: Ibf70fb66f001b6d11b99c21904ed22015452b421