Updated pywikibot/core Project: pywikibot/externals/httplib2  435717f722003fd2e2940d94a9e0e5d0b32d4a7d
Fix nosetests breakage

The last commit broke nosetests:

File "__init__.py",
line 7, in <module>
    del sys.modules['httplib2']
KeyError: 'httplib2'

Change-Id: Iff36327735b9e535bda2968ac17032efdaf76d24