site_tests.test_search_where_title: Use assertIn instead of assertTrue
This way unittest will produce a more descriptive error message by showing
    AssertionError: 'wiki' not found in <page title>
instead of
    AssertionError: False is not true

Change-Id: I98059d53d5b2be1673743503e4809ceab7e7e869