[bugfix] Enable replacements with bool(replacements) is False to be imported
If a replacement is given with _add_deprecated_attr method and its
boolean result is false it cannot be imported and an ImportError occurs:
ImportError: cannot import name '<replacement>' from '<module>'.
Therefore check whether a replacement was given explicitly.

Change-Id: I1158e83c8a40857766d43158e636412701ae6b74