[tests] Follow-up patch for T334378
This is necessary due to another SystemError:
SystemError: <built-in method split of str object at 0x7f21bee950b0>
returned a result with an exception set

Bug: T334378
Change-Id: If746cbe93844cac6793c50c590e2aafc9c6031cb